sudo: false
language: python
python:
  - "2.7"
  - "3.5"
before_install:
 # Install lcov
 - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
 - tar xf lcov_1.11.orig.tar.gz
 - mkdir $HOME/usr
 - export PATH=$HOME/usr/bin:$PATH
 - make -C lcov-1.11/ install PREFIX=$HOME
 #Setup conda for faster installs
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest
 - source activate test-environment
# command to install dependencies
install:
 - pip install 'coverage==4.1' --force-reinstall # necessary bc of backward incompatible change in 4.2 about combining reports
 - pip install pytest-cov
 - easy_install --upgrade requests
 - python setup.py build_ext --coverage --inplace
 - python setup.py develop
script:
# only wait longer for orbit integrations
 - pytest -v tests/ --cov wendy --cov-config .coveragerc_travis
after_success:
 # Generate lcov output 
 - lcov --capture --base-directory . --directory build/temp.linux-x86_64-2.7/wendy/ --no-external --output-file coverage_full.info
 # Codecov
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then bash <(curl -s https://codecov.io/bash); fi
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
