dist: xenial
sudo: false
language: python
python:
  - "2.7"
  - "3.7"
env:
  global:
    - PYTHON_COVREPORTS_VERSION=3.7 # Version for which reports are uploaded
before_install:
 # Install lcov
 - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
 - tar xf lcov_1.11.orig.tar.gz
 - mkdir $HOME/usr
 - export PATH=$HOME/usr/bin:$PATH
 - make -C lcov-1.11/ install PREFIX=$HOME
 #Setup conda for faster installs
 - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest
 - source activate test-environment
# command to install dependencies
install:
 - pip install 'coverage==4.1' --force-reinstall # necessary bc of backward incompatible change in 4.2 about combining reports
 - pip install pytest-cov
 - easy_install --upgrade requests
 - python setup.py build_ext --coverage --inplace
 - python setup.py develop
script:
# only wait longer for orbit integrations
 - pytest -v tests/ --cov wendy --cov-config .coveragerc_travis
after_success:
 # Generate lcov output 
 - lcov --capture --base-directory . --directory build/temp.linux-x86_64-$PYTHON_COVREPORTS_VERSION/wendy/ --no-external --output-file coverage_full.info
 # Codecov, need to edit bash uploader for incorrect TRAVIS_PYTHON_VERSION environment variable matching, at least until codecov/codecov-bash#133 is resolved
 - curl -s https://codecov.io/bash > .codecov
 - sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' .codecov
 - chmod +x .codecov
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then ./.codecov -X gcov; fi
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
